-- Apple Analytics Curated Tables Setup
-- These tables point to Parquet files generated by the curator
-- Partition structure: dt=YYYY-MM-DD/app_id=NNNNNN/

-- Drop existing curated tables if they exist
DROP TABLE IF EXISTS appstore.curated_downloads;
DROP TABLE IF EXISTS appstore.curated_engagement;
DROP TABLE IF EXISTS appstore.curated_reviews;

-- ============================================================================
-- CURATED DOWNLOADS TABLE (Parquet)
-- ============================================================================
CREATE EXTERNAL TABLE appstore.curated_downloads (
    metric_date string,
    app_name string,
    app_id string,
    download_type string,
    source_type string,
    territory string,
    device string,
    platform_version string,
    page_type string,
    total_downloads bigint
)
PARTITIONED BY (dt string, app_id_partition string)
STORED AS PARQUET
LOCATION 's3://skidos-apptrack/appstore/curated/downloads/'
TBLPROPERTIES (
    'projection.enabled'='true',
    'projection.dt.type'='date',
    'projection.dt.format'='yyyy-MM-dd',
    'projection.dt.range'='2024-01-01,NOW',
    'projection.app_id_partition.type'='injected',
    'storage.location.template'='s3://skidos-apptrack/appstore/curated/downloads/dt=${dt}/app_id=${app_id_partition}/'
);

-- ============================================================================
-- CURATED ENGAGEMENT TABLE (Parquet)
-- ============================================================================
CREATE EXTERNAL TABLE appstore.curated_engagement (
    metric_date string,
    app_name string,
    app_id string,
    source_type string,
    page_type string,
    territory string,
    device string,
    platform_version string,
    event_type string,
    engagement_type string,
    impressions bigint,
    impressions_unique bigint
)
PARTITIONED BY (dt string, app_id_partition string)
STORED AS PARQUET
LOCATION 's3://skidos-apptrack/appstore/curated/engagement/'
TBLPROPERTIES (
    'projection.enabled'='true',
    'projection.dt.type'='date',
    'projection.dt.format'='yyyy-MM-dd',
    'projection.dt.range'='2024-01-01,NOW',
    'projection.app_id_partition.type'='injected',
    'storage.location.template'='s3://skidos-apptrack/appstore/curated/engagement/dt=${dt}/app_id=${app_id_partition}/'
);

-- ============================================================================
-- CURATED REVIEWS TABLE (Parquet)
-- ============================================================================
CREATE EXTERNAL TABLE appstore.curated_reviews (
    review_date string,
    app_name string,
    app_id string,
    territory string,
    review_id string,
    rating int,
    title string,
    review_text string,
    version string,
    developer_response string
)
PARTITIONED BY (dt string, app_id_partition string)
STORED AS PARQUET
LOCATION 's3://skidos-apptrack/appstore/curated/reviews/'
TBLPROPERTIES (
    'projection.enabled'='true',
    'projection.dt.type'='date',
    'projection.dt.format'='yyyy-MM-dd',
    'projection.dt.range'='2024-01-01,NOW',
    'projection.app_id_partition.type'='injected',
    'storage.location.template'='s3://skidos-apptrack/appstore/curated/reviews/dt=${dt}/app_id=${app_id_partition}/'
);

-- ============================================================================
-- VIEWS FOR EASY ACCESS (Optional - work with raw data directly)
-- ============================================================================

-- Daily Downloads Summary View
CREATE OR REPLACE VIEW appstore.v_daily_downloads AS
SELECT 
    dt as report_date,
    app_id,
    app_name,
    territory,
    SUM(counts) as total_downloads
FROM appstore.raw_downloads
GROUP BY dt, app_id, app_name, territory;

-- Daily Engagement Summary View  
CREATE OR REPLACE VIEW appstore.v_daily_engagement AS
SELECT
    dt as report_date,
    app_id,
    app_name,
    territory,
    source_type,
    SUM(counts) as total_impressions
FROM appstore.raw_engagement
GROUP BY dt, app_id, app_name, territory, source_type;
